// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckListController from "./check_list_controller"
application.register("check-list", CheckListController)

import DrinkMakingFormController from "./drink_making_form_controller"
application.register("drink-making-form", DrinkMakingFormController)

import FacetsController from "./facets_controller"
application.register("facets", FacetsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeIndexController from "./home_index_controller"
application.register("home-index", HomeIndexController)

import IngredientsSelectController from "./ingredients_select_controller"
application.register("ingredients-select", IngredientsSelectController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TagSelectorController from "./tag_selector_controller"
application.register("tag-selector", TagSelectorController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
