// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FacetsController from "./facets_controller"
application.register("facets", FacetsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeIndexController from "./home_index_controller"
application.register("home-index", HomeIndexController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
